### PR TITLE
consul_exporter support

### PR DESCRIPTION
**Pull request by robbiet480**
This adds consul_exporter. It's basically a clone of the node_exporter code, with node replaced.

### CODE REVIEW

**Comment by robbiet480** [comment]
@William-Yeh Can you re-run the circle tests? Looks like it failed because of a timeout + some SSL problem with CircleCI when trying to contact Github.

**Comment by trumant** [comment]
@William-Yeh - I'd like to see this merged, would definitely benefit my team that is already using the role.

**Comment by William-Yeh** [comment]
@trumant Could you recommend a good Consul role for Debian/Ubuntu/CentOS so that the `consul_exporter` code can be automated tested in Travis CI and CircleCI?

**Comment by trumant** [comment]
@William-Yeh - Let me see if I can get this working: https://github.com/jivesoftware/ansible-consul/pull/11 which may help solve the testing challenge.

**Comment by trumant** [comment]
@William-Yeh and @robbiet480 - I'm working on getting the tests updated to validate the consul_exporter install.

**Pull request merged**
