### PR TITLE
Reload node_exporter.service if unit file changed

### PR DESCRIPTION
**Pull request by czerasz**

### CODE REVIEW

**Comment by lhoss** [comment]
+1 to get this merged 👍 
( though I initially thought about a fix, that re-used the existing 'restart' handler, this way it's probably easier and clearer, also because for systemd you need the extra `daemon_reload:yes` option, not (yet) supported by the (old but) generic `service` task )

**Comment by ecksun** [comment]
How come you don't use a handler?

**Comment by lhoss** [comment]
> How come you don't use a handler?

not my PR/fix
but yeah, we could def. move the new (systemd specific) restart task to the handlers, and then just 
`notify: restart node_exporter systemd service`

**Comment by lhoss** [comment]
@William-Yeh any chance for a merge ?

**Comment by lhoss** [comment]
@ecksun I improved this patch using a handler (and fixing for the non-systemd case) https://github.com/teralytics/ansible-prometheus/pull/3
but the PR isn't based on latest master (here)

ps: In the hope to bring the master branch up to speed: #64

**Comment by czerasz** [comment]
[Version with handler](https://github.com/teralytics/ansible-prometheus/pull/3) looks much better! Good job @lhoss! Closing PR

**Pull request closed without merging**
