### PR TITLE
Allow for installation of components from Git

### PR DESCRIPTION
**Pull request by robbiet480**
I needed to get a more recent version of Prometheus & AlertManager installed on our systems but there weren't yet releases cut for either of them. This PR adds the ability to get the source from Github and use the Prometheus provided Makefiles to download Go and compile Prometheus, AlertManager or node_exporter. It does not install Go to the system, merely uses it's own local copy temporarily.

### CODE REVIEW

**Comment by William-Yeh** [comment]
Thanks, robbiet480.

Personally I prefer official releases to release candidates. But if appropriate playbooks are available, I'll be happy to incorporate them.

As for your `install-from-git` PR, I have some problems when executing the `[build node_exporter]` step under Ubuntu 14.04:

```
TASK: [build node_exporter] ***************************************************
failed: [main] => {"changed": true, "cmd": ["make"], "delta": "0:02:05.575880", "end": "2015-09-19 12:50:50.939573", "rc": 2, "start": "2015-09-19 12:48:45.363693", "warnings": []}
stderr:   % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100    87  100    87    0     0    308      0 --:--:-- --:--:-- --:--:--   309
100 74.2M  100 74.2M    0     0   632k      0  0:02:00  0:02:00 --:--:-- 2861k
go: missing Git command. See https://golang.org/s/gogetcmd
package github.com/prometheus/client_golang/prometheus: exec: "git": executable file not found in $PATH
go: missing Git command. See https://golang.org/s/gogetcmd
package github.com/prometheus/log: exec: "git": executable file not found in $PATH
go: missing Git command. See https://golang.org/s/gogetcmd
package github.com/beevik/ntp: exec: "git": executable file not found in $PATH
go: missing Git command. See https://golang.org/s/gogetcmd
package github.com/golang/protobuf/proto: exec: "git": executable file not found in $PATH
go: missing Git command. See https://golang.org/s/gogetcmd
package github.com/prometheus/client_model/go: exec: "git": executable file not found in $PATH
go: missing Git command. See https://golang.org/s/gogetcmd
package github.com/prometheus/common/expfmt: exec: "git": executable file not found in $PATH
go: missing Git command. See https://golang.org/s/gogetcmd
package github.com/prometheus/procfs: exec: "git": executable file not found in $PATH
go: missing Git command. See https://golang.org/s/gogetcmd
package github.com/soundcloud/go-runit/runit: exec: "git": executable file not found in $PATH
make: *** [dependencies-stamp] Error 1
stdout: Go version 1.5.1 required but not found in PATH.
About to download and install go1.5.1 to /tmp/node_exporter-master/.build/go1.5.1
Abort now if you want to manually install it system-wide instead.

mkdir -p /tmp/node_exporter-master/.build/go1.5.1
curl -L https://golang.org/dl/go1.5.1.linux-amd64.tar.gz | tar -C /tmp/node_exporter-master/.build/go1.5.1 --strip 1 -xz
mkdir -p /tmp/node_exporter-master/.build/gopath/src/github.com/prometheus/
ln -s /tmp/node_exporter-master /tmp/node_exporter-master/.build/gopath/src/github.com/prometheus/node_exporter
GOROOT=/tmp/node_exporter-master/.build/go1.5.1 GOPATH=/tmp/node_exporter-master/.build/gopath /tmp/node_exporter-master/.build/go1.5.1/bin/go get -d

FATAL: all hosts have already failed -- aborting
```

**Comment by robbiet480** [comment]
@William-Yeh ah, [Prometheus says](https://github.com/prometheus/prometheus/blob/1a3ee28cd261c31833201f4de88da75166407624/README.md#use-make) that their Makefile requires `curl`, `git`, `gzip`, `hg`. I'll add platform specific code to install all dependencies from Yum or Apt shortly.

**Comment by robbiet480** [comment]
@William-Yeh done! If you have a CentOS/Redhat machine handy, can you test on that? I looked up all the package names for that platform and it should be fine, but might be good to check.

**Comment by robbiet480** [comment]
BTW, I got the tip for that action statement from [this Gist](https://gist.github.com/hostmaster/8385567). Pretty cool way to install the same set of packages across platforms without needing to work with conditionals

**Comment by robbiet480** [comment]
@William-Yeh I'm unsure why tests are failing since it appears the `docker build -f test/Dockerfile-ubuntu14.04 -t prometheus_trusty .` completed successfully (and the `grep '^prometheus_target_interval_length_seconds' result-ubuntu14.04` failed later)

**Comment by William-Yeh** [comment]
In addition to merge this 'install-from-git' PR, I do the following:
- Fix conflicts;
- Refactor playbooks;
- Add test cases for this commit.

**Comment by robbiet480** [comment]
@William-Yeh :+1: glad to see this merged, thanks!!

**Comment by lae** [comment]
I've actually been following this as well, thanks you two. :+1:

**Pull request merged**
