### PR TITLE
Restart node_exporter on failure.

### PR DESCRIPTION
**Pull request by ogavrisevs**
IMO its good thing to ensure service in systemd always is running .

### CODE REVIEW

**Comment by ogavrisevs** [comment]
I dont know how to restart Travis build.

**Comment by thapakazi** [comment]
:+1:  for the changes @ogavrisevs I also need these.
there seems some problem in ci, any chance somebody looking into it. Seems some prometheus  build error.

**Comment by lhoss** [comment]
+1 (need more maintainers for this role!)
ps: this would also include recent PR https://github.com/William-Yeh/ansible-prometheus/pull/61

**Comment by William-Yeh** [comment]
Updated since https://github.com/William-Yeh/ansible-prometheus/commit/89e8a511212708d27326d0532a22f67e5e0d3679

Thank you.

**Pull request closed without merging**
