### PR TITLE
systemd dependency chain

### PR DESCRIPTION
**Pull request by cangus**
Ensures that the service gets restarted when the host reboots

### CODE REVIEW

**Comment by selslack** [comment]
This is must have. Can you merge it, please?

**Comment by czerasz** [comment]
This PR is really important! Pls merge

**Comment by dhoppe** [comment]
This pull request should be closed, because #35 provides a more sophisticated solution.

**Comment by czerasz** [comment]
Should be closed but only if **this change is also implemented in #35**

**Pull request closed without merging**
